# Site settings
title: Bruno Passos - Web designer and front-end developer
email: passosbruno@gmail.com
#description: ""
#baseurl: ""
url: "http://brunopassos.com"
twitter_username: brunopassos
github_username:  bpassos

# Build settings
markdown: kramdown
permalink: pretty
